### ISSUE TITLE
The new release is breaking app the mvc apps

### ISSUE THREAD

**Issue by ibnsultan** [leafsphp/blade#4]
The new release is breaking app the mvc apps, it results to fatal error 

Error: `Call to a member function make() on null`
File: src\Blade.php
Line: 41

**Comment by mychidarko** [comment]
Try updating all your leaf deps to their latest versions and then using this updated config https://github.com/leafsphp/leafMVC/blob/v3.x/config/view.php

**Comment by ibnsultan** [comment]
results to another error `Call to a member function configure() on null`

https://github.com/leafsphp/leafMVC/blob/v3.x/config/view.php
```php
'config' => function ($config) {
        \Leaf\Config::get('views.blade')->configure($config['views'], $config['cache']);
  },
```

**Comment by mychidarko** [comment]
Hmm weird, it shouldn't break. But anyway you can fix this by updating your public/index.php file. Replace the line where you attach blade with this

```php
Leaf\Config::attachView(\Leaf\Blade::class);
```

**Comment by ibnsultan** [comment]
The issue's been resolved
