### ISSUE TITLE
Adding custom Directives

### ISSUE THREAD

**Issue by ibnsultan** [leafsphp/blade#5]
@mychidarko 
How do I add a custom Directives for the blade engine to the app without editing the main package

**Comment by mychidarko** [comment]
It should work the same way

```php
$blade->directive('datetime', function ($expression) {
    return "<?php echo with({$expression})->format('F d, Y g:i a'); ?>";
});
```

**Comment by ibnsultan** [comment]
Am aware of that but where am stack is with which instance I need to work with because `$blade` itself is not a global or constant variable, so it needs to be an instance of something.

I've tried with the `Leaf\Blade` and the defined `config` instance from `config/view.php` but both of them either result to null or errors, could you please provide me with a descriptive example.

@mychidarko
